#!/bin/sh

ISO8601='^[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}T[0-9]\{2\}:[0-9]\{2\}$'

hours() {
  echo "scale=2;$1/60/60" | bc
}

now() {
  date +%FT%H:%M
}

has_unfinished_records() {
  grep "$ISO8601" "$1" >/dev/null
}

if [ $# -lt 1 ]; then
  echo >&2 "usage: $0 FILE [start|stop]"
  exit 1
elif [ ! -w "$1" ] || [ ! -f "$1" ]; then
  echo >&2 "File $1 is not writable. Aborting."
  exit 1
fi

case "$2" in
  start)
    if has_unfinished_records "$1"; then
      echo >&2 "There are unfinished records. Not starting a new one."
    else
      now >>"$1"
    fi ;;
  stop)
    if has_unfinished_records "$1"; then
      sed -i "s/$ISO8601/& $(now)/" "$1"
    else
      echo >&2 "There are no unfinished records to end."
    fi ;;
  "")
    total_duration=0
    while read -r line; do
      set $line
      if [ $# -lt 2 ]; then
        h_begin=$(date -d "$1" +%s)
        h_now=$(date +%s)
        h_current_duration=$(( h_now - h_begin ))
        printf '\e[33m%5.2f\e[0mh\t%s -\n' "$(hours "$h_current_duration")" "$1"
      else
        h_begin=$(date -d "$1" +%s)
        h_end=$(date -d "$2" +%s)
        h_duration=$(( h_end - h_begin ))
        total_duration=$((total_duration + h_duration))
        printf '\e[32m%5.2f\e[0mh\t%s - %s\n' "$(hours "$h_duration")" "$1" "$2"
      fi
    done < "$1"
    printf -- '------\n\e[32m%5.2f\e[0mh\n' "$(hours $total_duration)" ;;
esac
